cmake_minimum_required(VERSION 3.28)
project(Rutgers_ECE_451_NetworkCentricProgramming)

set(CMAKE_C_STANDARD 23)
set(CMAKE_CXX_STANDARD 23)

add_executable(S01_In_Class_Primes sessions/01/inclass/primes.cpp)
add_executable(S01_In_Class_SaveWebP sessions/01/inclass/savewebp.cpp)
add_executable(S01_WriteImg sessions/01/writeimg.cpp)

add_executable(S02_Lifetime_Scope sessions/02/01lifetime_scope.c)
add_executable(S02_Primitives sessions/02/02primitives.c)
add_executable(S02_Functions_And_Types sessions/02/03functions_and_types.cpp)
add_executable(S02_High_Speed_IO sessions/02/04high_speed_io.cpp)
add_executable(S02_Bench sessions/02/05bench.cpp)

add_executable(S03_Pointers sessions/03/01_pointers.cpp)
add_executable(S03_Bounds_Error sessions/03/02bounds_error.cpp)
add_executable(S03_Const_Pointer sessions/03/03_constpointer.cpp)
add_executable(S03_Calling_Kernel sessions/03/04_calling_kernel.cpp)
add_executable(S03_BadInline sessions/03/badinline.cpp)
add_executable(S03_Inline_Example sessions/03/inline_example.cpp)
add_executable(S03_Declarations sessions/03/declarations.cpp)
add_executable(S03_MultipleInclude sessions/03/multipleinclude.cpp)

add_executable(S04_A sessions/04/a.cpp)
add_executable(S04_B sessions/04/b.cpp)
add_executable(S04_A2 sessions/04/a2.cpp)
add_executable(S04_B2 sessions/04/b2.cpp)
add_executable(S04_MathLib sessions/04/mathlib.cpp)
add_executable(S04_TestMathLib sessions/04/testmathlib.cpp)
add_executable(S04_BadTestMathLib sessions/04/badtestmathlib.cpp)
add_executable(S04_WriteFile sessions/04/writefile.cpp)

add_executable(S05_Points sessions/05/points.cpp)
add_executable(S05_Client sessions/05/client.cpp)
add_executable(S05_Server sessions/05/server.cpp)
add_executable(S05_Threads sessions/05/threads.cpp)
